# (c) Copyright [2021] Micro Focus or one of its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-setup-tls-server-mode
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -o errexit
    set -o xtrace

    SERVER_CRT=$(cat /certs/tls.crt)
    SERVER_KEY=$(cat /certs/tls.key)
    POD_NAME=$(kubectl get pods --selector=app.kubernetes.io/name=vertica,vertica.com/usage=server -o jsonpath="{.items[0].metadata.name}")

    cat << EOF > /tmp/setup.sh
    #!/bin/sh
    set -o xtrace
    set -o errexit

    SU_PASSWD=\$(cat /etc/podinfo/superuser-passwd 2> /dev/null || :)
    if [ -n "\$SU_PASSWD" ]
    then
      VSQL_PASSWD_OPT="-w \$SU_PASSWD"
    fi

    vsql \$VSQL_PASSWD_OPT -c "select set_config_parameter('SSLCertificate', '$SERVER_CRT');"
    vsql \$VSQL_PASSWD_OPT -c "select set_config_parameter('SSLPrivateKey', '$SERVER_KEY');"
    vsql \$VSQL_PASSWD_OPT -c "select set_config_parameter('EnableSSL','1');"
    EOF
    kubectl cp /tmp/setup.sh $POD_NAME:/home/dbadmin/setup.sh
    kubectl exec $POD_NAME -i -- sh /home/dbadmin/setup.sh
---
apiVersion: testing.kyma-project.io/v1alpha1
kind: TestDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: test-setup-tls-server-mode
spec:
  description: |
    Setup TLS for the database in server mode.  This has to be run after the database has been created.
  template:
    spec:
      containers:
        - name: test
          image: quay.io/helmpack/chart-testing:v3.3.1
          command: ["/bin/entrypoint.sh"]
          volumeMounts:
            - name: entrypoint-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: server-tls-parms
              mountPath: /certs
              readOnly: true
      volumes:
        - name: entrypoint-volume
          configMap:
            defaultMode: 0700
            name: script-setup-tls-server-mode
        - name: server-tls-parms
          secret:
            secretName: {{ .Values.tls.serverSecret }}
