# (c) Copyright [2021] Micro Focus or one of its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-verify-client-access-test
data:
  test.py: |-
    #!/usr/bin/env python

    import vertica_k8s_tools
    with vertica_k8s_tools.connect({{ .Release.Namespace | quote }}, {{ .Values.clusterReleaseName | quote }}) as conn:
      cur = conn.cursor()
      cmds = [ { "sql": "drop table if exists t1" },
               { "sql": "create table t1 (c1 int)" },
               { "sql": "insert into t1 values (1)" },
               { "sql": "select * from t1", "fetch": True,
                 "expected": [[1]] },
               { "sql": "drop table t1" } ]
      for c in cmds:
        print(c["sql"])
        cur.execute(c["sql"])
        print("  -> SUCCESS")
        if "fetch" in c and c["fetch"]:
          res = cur.fetchall()
          print("  fetchall(): {}".format(res))
          assert(res == c["expected"])
---
apiVersion: testing.kyma-project.io/v1alpha1
kind: TestDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: test-verify-client-access
spec:
  description: |
    Verifies access to the external service through port 5433.  It does this
    by connecting using the python client.
  template:
    spec:
      containers:
        - name: test
          image: {{ .Values.pythonToolsRepo}}:{{ .Values.pythonToolsTag }}
          command: ["/root/test.py"]
          volumeMounts:
            - name: test-script
              mountPath: /root/test.py
              readOnly: true
              subPath: test.py
      volumes:
        - name: test-script
          configMap:
            defaultMode: 0777
            name: script-verify-client-access-test
